apiVersion: v1
kind: Service
metadata:
  name: {{ include "sklad.fullname" . }}-web
  labels:
    {{- include "sklad.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "sklad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
