apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sklad
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/vutratenko/charts
    chart: sklad
    targetRevision: "0.1.1"
    helm:
      valuesObject:
        api:
          existingSecret: sklad-api-secrets
        ingress:
          enabled: false
          host: sklad.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: sklad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
