apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sklad
  namespace: shturval-cd
spec:
  project: sklad
  source:
    repoURL: oci://ghcr.io/vutratenko/charts/sklad
    path: "."
    targetRevision: "0.1.17"
    helm:
      valuesObject:
        api:
          existingSecret: sklad-api-secrets
          env:
            OIDC_REDIRECT_URI: https://sklad.sion2k.ru/oauth/callback
            OIDC_USERINFO_URL: http://nextcloud-aio-apache.nextcloud.svc.cluster.local:9888/ocs/v2.php/cloud/user?format=json
            OIDC_USERINFO_HOST: cloud.sion2k.ru
        ingress:
          enabled: true
          className: nginx
          host: sklad.sion2k.ru
          annotations:
            cert-manager.io/cluster-issuer: corp-acme
          tls:
            - secretName: sklad-tls
              hosts:
                - sklad.sion2k.ru
  destination:
    server: https://kubernetes.default.svc
    namespace: sklad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
