apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sklad
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/vutratenko/charts
    chart: sklad
    targetRevision: "0.1.3"
    helm:
      valuesObject:
        api:
          existingSecret: sklad-api-secrets
          env:
            OIDC_REDIRECT_URI: https://sklad.sion2k.ru/oauth/callback
        ingress:
          enabled: true
          className: nginx
          host: sklad.sion2k.ru
          annotations:
            cert-manager.io/issuer: corp-acme
          tls:
            - secretName: sklad-tls
              hosts:
                - sklad.sion2k.ru
  destination:
    server: https://kubernetes.default.svc
    namespace: sklad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
